#ifndef LOGGINGCATEGORIES_HPP
#define LOGGINGCATEGORIES_HPP

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logDebug)
Q_DECLARE_LOGGING_CATEGORY(logInfo)
Q_DECLARE_LOGGING_CATEGORY(logWarning)
Q_DECLARE_LOGGING_CATEGORY(logCritical)

#endif  // LOGGINGCATEGORIES_HPP
